language: en
pipeline:
  - name: SpacyNLP
    model: external_data/spacy.word2vec.model
  - name: profanity_analyzer.ProfanityAnalyzer
  - name: SpacyTokenizer
  - name: RegexFeaturizer 
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 100
    random_seed: 3
  - name: EntitySynonymMapper

policies:
  - name: MemoizationPolicy
    max_history: 5
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: FormPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.4
    core_threshold: 0.4
    ambiguity_threshold: 0.1
    fallback_action_name: action_my_fallback